name: App Test
on:
  push:
    branches:
      - master

jobs:
  code_testing:
    runs-on: ubuntu-latest
    environment: Production
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install
        run: |
          yarn install
      - name: eslint
        run: yarn lint
      - name: test
        run: |
          yarn test
      - name: Cypress e2e test
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./src
          build: yarn run build
          start: yarn run start
          wait-on: 'http://localhost:3000'
        env:
          NEXT_PUBLIC_REACT_APP_API_KEY: ${{ secrets.NEXT_PUBLIC_REACT_APP_API_KEY }}
          NEXT_PUBLIC_REACT_APP_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_REACT_APP_AUTH_DOMAIN }}
          NEXT_PUBLIC_REACT_APP_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_REACT_APP_DATABASE_URL }}
          NEXT_PUBLIC_REACT_APP_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_REACT_APP_PROJECT_ID }}
          NEXT_PUBLIC_REACT_APP_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_REACT_APP_STORAGE_BUCKET }}
          NEXT_PUBLIC_REACT_APP_APP_ID: ${{ secrets.NEXT_PUBLIC_REACT_APP_APP_ID }}
          NEXT_PUBLIC_REACT_APP_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_REACT_APP_MEASUREMENT_ID }}
          NEXT_PUBLIC_GITHUB_API_PATH: ${{ secrets.NEXT_PUBLIC_GITHUB_API_PATH }}
          NEXT_PUBLIC_GITHUB_TOKEN: ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
          NEXT_PUBLIC_GITHUB_OWNER: ${{ secrets.NEXT_PUBLIC_GITHUB_OWNER }}
          NEXT_PUBLIC_GITHUB_NAME: ${{ secrets.NEXT_PUBLIC_GITHUB_NAME }}
          NEXT_PUBLIC_GITHUB_EXPRESSION: ${{ secrets.NEXT_PUBLIC_GITHUB_EXPRESSION }}
          NEXT_PUBLIC_GITHUB_PAGE_EXPRESSION: ${{ secrets.NEXT_PUBLIC_GITHUB_PAGE_EXPRESSION }}
          CYPRESS_REACT_APP_API_KEY: ${{ secrets.NEXT_PUBLIC_REACT_APP_API_KEY }}
          CYPRESS_REACT_APP_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_REACT_APP_AUTH_DOMAIN }}
          CYPRESS_REACT_APP_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_REACT_APP_DATABASE_URL }}
          CYPRESS_REACT_APP_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_REACT_APP_PROJECT_ID }}
          CYPRESS_REACT_APP_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_REACT_APP_STORAGE_BUCKET }}
          CYPRESS_REACT_APP_APP_ID: ${{ secrets.NEXT_PUBLIC_REACT_APP_APP_ID }}
          CYPRESS_REACT_APP_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_REACT_APP_MEASUREMENT_ID }}
          CYPRESS_GITHUB_API_PATH: ${{ secrets.NEXT_PUBLIC_GITHUB_API_PATH }}
          CYPRESS_TEST_UID: ${{ secrets.CYPRESS_TEST_UID }}
          SERVICE_ACCOUNT: ${{ secrets.CYPRESS_SERVICE_ACCOUNT }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
